{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 22, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_success_flow", "rerun": "0"}, "1": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_out_of_stock_flow", "rerun": "0"}, "2": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_payment_failure_flow", "rerun": "0"}, "3": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_cancel_order_status_1", "rerun": "0"}, "4": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_cancel_order_status_2", "rerun": "0"}, "5": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_cancel_order_status_3", "rerun": "0"}, "6": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_cancel_order_status_4_fail", "rerun": "0"}, "7": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_cancel_order_status_5_fail", "rerun": "0"}, "8": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_update_order_to_shiped", "rerun": "0"}, "9": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_update_order_to_shiped_fail_status_1", "rerun": "0"}, "10": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_update_order_to_shiped_fail_status_2", "rerun": "0"}, "11": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_update_order_to_shiped_fail_status_3", "rerun": "0"}, "12": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_update_order_to_shiped_fail_status_6", "rerun": "0"}, "13": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_order_fail_with_card_type_4", "rerun": "0"}, "14": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_order_fail_with_card_type_0", "rerun": "0"}, "15": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_order_fail_with_card_type_negative", "rerun": "0"}, "16": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_create_order_with_wrong_security_number", "rerun": "0"}, "17": {"status": "FAIL", "message": "   TypeError: create_msg_checkout() got an unexpected keyword argument 'cardnumber'\n", "test_name": "test_create_order_with_wrong_credit_card_number", "rerun": "0"}, "18": {"status": "FAIL", "message": "   AssertionError: assert {'status': 40...ection-6.5.4'} == {'city': 'Red...n': None, ...}\n     Differing items:\n     {'status': 404} != {'status': 'shipped'}\n     Left contains 3 more items:\n     {'title': 'Not Found',\n      'traceId': '00-fabf17606382769ff42ba4330c3d6d40-9578580445877707-00',\n      'type': 'https://tools.ietf.org/html/rfc7231#section-6.5.4'}\n     Right contains 9 more items:...\n     \n     ...Full output truncated (18 lines hidden), use '-vv' to show\n", "test_name": "test_get_user_order_by_id", "rerun": "0"}, "19": {"status": "FAIL", "message": "   assert 404 == 401\n    +  where 404 = <Response [404]>.status_code\n    +    where <Response [404]> = <bound method OrderingAPI.get_order_by_id of <utils.api.ordering_api.OrderingAPI object at 0x0000021D03E33D50>>(42)\n    +      where <bound method OrderingAPI.get_order_by_id of <utils.api.ordering_api.OrderingAPI object at 0x0000021D03E33D50>> = <utils.api.ordering_api.OrderingAPI object at 0x0000021D03E33D50>.get_order_by_id\n    +        where <utils.api.ordering_api.OrderingAPI object at 0x0000021D03E33D50> = OrderingAPI()\n", "test_name": "test_get_user_order_by_id_of_diffrent_user", "rerun": "0"}, "20": {"status": "FAIL", "message": "   TypeError: OrderingAPI.__init__() takes 1 positional argument but 3 were given\n", "test_name": "test_get_user_orders", "rerun": "0"}, "21": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_update_order_to_shiped_to_diffrent_user", "rerun": "0"}}, "suite_name": "test_eshop.py"}}}, "date": "March 19, 2023", "start_time": 1679229512.230779, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "22", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "22"}