{"content": {"suites": {"0": {"status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 3, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_call_the_ordering_api", "rerun": "0"}, "1": {"status": "FAIL", "message": "       requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localnpipe/v1.41/containers/311fbdff256ed6dc245971bac1d750301b9473f5f7a18d0b3c7e1de023c08d6f/pause\n   docker.errors.APIError: 409 Client Error for http+docker://localnpipe/v1.41/containers/311fbdff256ed6dc245971bac1d750301b9473f5f7a18d0b3c7e1de023c08d6f/pause: Conflict (\"Container 311fbdff256ed6dc245971bac1d750301b9473f5f7a18d0b3c7e1de023c08d6f is already paused\")\n", "test_name": "test_mss_order", "rerun": "0"}, "2": {"status": "FAIL", "message": "           AssertionError: assert 'submitted' == 'awaitingvalidation'\n             - awaitingvalidation\n             + submitted\n", "test_name": "test_mss_order2", "rerun": "0"}, "3": {"status": "FAIL", "message": "           TypeError: create_order() takes 1 positional argument but 2 were given\n", "test_name": "test_out_of_stock_quantity", "rerun": "0"}}, "suite_name": "tests/test_eShop.py"}}}, "date": "March 13, 2023", "start_time": 1678706633.8082216, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "1", "fail": "3", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "4"}