{"content": {"suites": {"0": {"status": {"total_pass": 8, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 9, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_call_the_ordering_api", "rerun": "0"}, "1": {"status": "FAIL", "message": "       requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localnpipe/v1.41/containers/311fbdff256ed6dc245971bac1d750301b9473f5f7a18d0b3c7e1de023c08d6f/pause\n   docker.errors.APIError: 409 Client Error for http+docker://localnpipe/v1.41/containers/311fbdff256ed6dc245971bac1d750301b9473f5f7a18d0b3c7e1de023c08d6f/pause: Conflict (\"Container 311fbdff256ed6dc245971bac1d750301b9473f5f7a18d0b3c7e1de023c08d6f is already paused\")\n", "test_name": "test_mss_order", "rerun": "0"}, "2": {"status": "FAIL", "message": "           AssertionError: assert 'submitted' == 'awaitingvalidation'\n             - awaitingvalidation\n             + submitted\n", "test_name": "test_mss_order2", "rerun": "0"}, "3": {"status": "FAIL", "message": "           TypeError: create_order() takes 1 positional argument but 2 were given\n", "test_name": "test_out_of_stock_quantity", "rerun": "0"}, "4": {"status": "FAIL", "message": "           NameError: name 'expected_step_1' is not defined\n", "test_name": "test_temp", "rerun": "0"}, "5": {"status": "FAIL", "message": "           AssertionError: assert 'submitted' == 'awaitingvalidation'\n             - awaitingvalidation\n             + submitted\n", "test_name": "test_payment_failed", "rerun": "0"}, "6": {"status": "FAIL", "message": "           AssertionError: assert 'submitted' == 'awaitingvalidation'\n             - awaitingvalidation\n             + submitted\n", "test_name": "test_update_check_successfully_status_4_to_5", "rerun": "0"}, "7": {"status": "PASS", "message": "", "test_name": "test_update_check_failed_status_2_to_5", "rerun": "0"}, "8": {"status": "PASS", "message": "", "test_name": "test_update_check_failed_status_3_to_5", "rerun": "0"}, "9": {"status": "FAIL", "message": "           AssertionError: assert 'submitted' == 'awaitingvalidation'\n             - awaitingvalidation\n             + submitted\n", "test_name": "test_update_check_failed_status_5_to_6", "rerun": "0"}, "10": {"status": "FAIL", "message": "       requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localnpipe/v1.41/containers/311fbdff256ed6dc245971bac1d750301b9473f5f7a18d0b3c7e1de023c08d6f/pause\n   docker.errors.APIError: 409 Client Error for http+docker://localnpipe/v1.41/containers/311fbdff256ed6dc245971bac1d750301b9473f5f7a18d0b3c7e1de023c08d6f/pause: Conflict (\"Container 311fbdff256ed6dc245971bac1d750301b9473f5f7a18d0b3c7e1de023c08d6f is already paused\")\n", "test_name": "test_cancel_order_successfully_status_1_to_6", "rerun": "0"}, "11": {"status": "FAIL", "message": "           AssertionError: assert 'submitted' == 'awaitingvalidation'\n             - awaitingvalidation\n             + submitted\n", "test_name": "test_cancel_order_successfully_status_2_to_6", "rerun": "0"}, "12": {"status": "PASS", "message": "", "test_name": "test_cancel_order_successfully_status_3_to_6", "rerun": "0"}, "13": {"status": "PASS", "message": "", "test_name": "test_order_cancellation_failure_4_to_6", "rerun": "0"}, "14": {"status": "PASS", "message": "", "test_name": "test_order_cancellation_failure_5_to_6", "rerun": "0"}, "15": {"status": "PASS", "message": "", "test_name": "test_scalability_for_handling_high_volumes_of_orders", "rerun": "0"}, "16": {"status": "PASS", "message": "", "test_name": "test_reliability", "rerun": "0"}}, "suite_name": "tests/test_eShop.py"}}}, "date": "March 13, 2023", "start_time": 1678708540.7423778, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "8", "fail": "9", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "17"}