{"content": {"suites": {"0": {"status": {"total_pass": 8, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 3, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_call_the_ordering_api", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_mss", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_out_of_stock_quantity", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_payment_failed", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_update_check_successfully_status_4_to_5", "rerun": "0"}, "5": {"status": "PASS", "message": "", "test_name": "test_update_check_failed_status_2_to_5", "rerun": "0"}, "6": {"status": "PASS", "message": "", "test_name": "test_update_check_failed_status_3_to_5", "rerun": "0"}, "7": {"status": "PASS", "message": "", "test_name": "test_update_check_failed_status_5_to_6", "rerun": "0"}, "8": {"status": "FAIL", "message": "           assert 400 == 200\n            +  where 400 = <bound method OrderingAPI.put_cancel_order of <utils.api.ordering_api.OrderingAPI object at 0x0000018DA8C78410>>(2231)\n            +    where <bound method OrderingAPI.put_cancel_order of <utils.api.ordering_api.OrderingAPI object at 0x0000018DA8C78410>> = <utils.api.ordering_api.OrderingAPI object at 0x0000018DA8C78410>.put_cancel_order\n       Exception: assert 400 == 200\n        +  where 400 = <bound method OrderingAPI.put_cancel_order of <utils.api.ordering_api.OrderingAPI object at 0x0000018DA8C78410>>(2231)\n        +    where <bound method OrderingAPI.put_cancel_order of <utils.api.ordering_api.OrderingAPI object at 0x0000018DA8C78410>> = <utils.api.ordering_api.OrderingAPI object at 0x0000018DA8C78410>.put_cancel_order\n", "test_name": "test_cancel_order_successfully_status_1_to_6", "rerun": "0"}, "9": {"status": "FAIL", "message": "       assert 1 == 2\n       Exception: Failed in-create_order_test_and_expected_after_step_1 function assert 1 == 2\n       Exception: Failed in-create_order_test_and_expected_after_step_1 function assert 1 == 2\n", "test_name": "test_cancel_order_successfully_status_2_to_6", "rerun": "0"}, "10": {"status": "FAIL", "message": "           assert 400 == 200\n            +  where 400 = <bound method OrderingAPI.put_cancel_order of <utils.api.ordering_api.OrderingAPI object at 0x0000018DA7DE1B50>>(2233)\n            +    where <bound method OrderingAPI.put_cancel_order of <utils.api.ordering_api.OrderingAPI object at 0x0000018DA7DE1B50>> = <utils.api.ordering_api.OrderingAPI object at 0x0000018DA7DE1B50>.put_cancel_order\n       Exception: assert 400 == 200\n        +  where 400 = <bound method OrderingAPI.put_cancel_order of <utils.api.ordering_api.OrderingAPI object at 0x0000018DA7DE1B50>>(2233)\n        +    where <bound method OrderingAPI.put_cancel_order of <utils.api.ordering_api.OrderingAPI object at 0x0000018DA7DE1B50>> = <utils.api.ordering_api.OrderingAPI object at 0x0000018DA7DE1B50>.put_cancel_order\n", "test_name": "test_cancel_order_successfully_status_3_to_6", "rerun": "0"}}, "suite_name": "tests/test_non_functional.py"}}}, "date": "March 18, 2023", "start_time": 1679166974.2940738, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "8", "fail": "3", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "11"}