{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 21, "total_error": 1}, "tests": {"0": {"status": "FAIL", "message": "   TypeError: create_msg_checkout() missing 1 required positional argument: 'self'\n", "test_name": "test_success_flow", "rerun": "0"}, "1": {"status": "FAIL", "message": "   TypeError: create_msg_checkout() missing 1 required positional argument: 'self'\n", "test_name": "test_out_of_stock_flow", "rerun": "0"}, "2": {"status": "FAIL", "message": "   TypeError: create_msg_checkout() missing 1 required positional argument: 'self'\n", "test_name": "test_payment_failure_flow", "rerun": "0"}, "3": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_cancel_order_status_1", "rerun": "0"}, "4": {"status": "FAIL", "message": "   TypeError: create_msg_checkout() missing 1 required positional argument: 'self'\n", "test_name": "test_cancel_order_status_2", "rerun": "0"}, "5": {"status": "FAIL", "message": "   TypeError: create_msg_checkout() missing 1 required positional argument: 'self'\n", "test_name": "test_cancel_order_status_3", "rerun": "0"}, "6": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_cancel_order_status_4_fail", "rerun": "0"}, "7": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_cancel_order_status_5_fail", "rerun": "0"}, "8": {"status": "FAIL", "message": "   TypeError: create_msg_checkout() missing 1 required positional argument: 'self'\n", "test_name": "test_update_order_to_shiped", "rerun": "0"}, "9": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_update_order_to_shiped_fail_status_1", "rerun": "0"}, "10": {"status": "FAIL", "message": "   TypeError: create_msg_checkout() missing 1 required positional argument: 'self'\n", "test_name": "test_update_order_to_shiped_fail_status_2", "rerun": "0"}, "11": {"status": "FAIL", "message": "   TypeError: create_msg_checkout() missing 1 required positional argument: 'self'\n", "test_name": "test_update_order_to_shiped_fail_status_3", "rerun": "0"}, "12": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_update_order_to_shiped_fail_status_6", "rerun": "0"}, "13": {"status": "FAIL", "message": "   TypeError: create_msg_checkout() missing 1 required positional argument: 'self'\n", "test_name": "test_order_fail_with_card_type_4", "rerun": "0"}, "14": {"status": "FAIL", "message": "   TypeError: create_msg_checkout() missing 1 required positional argument: 'self'\n", "test_name": "test_order_fail_with_card_type_0", "rerun": "0"}, "15": {"status": "FAIL", "message": "   TypeError: create_msg_checkout() missing 1 required positional argument: 'self'\n", "test_name": "test_order_fail_with_card_type_negative", "rerun": "0"}, "16": {"status": "FAIL", "message": "   TypeError: create_msg_checkout() missing 1 required positional argument: 'self'\n", "test_name": "test_create_order_with_wrong_security_number", "rerun": "0"}, "17": {"status": "FAIL", "message": "   TypeError: create_msg_checkout() got an unexpected keyword argument 'cardnumber'\n", "test_name": "test_create_order_with_wrong_credit_card_number", "rerun": "0"}, "18": {"status": "FAIL", "message": "   NameError: name 'BearerTokenizer' is not defined\n", "test_name": "test_get_user_order_by_id", "rerun": "0"}, "19": {"status": "FAIL", "message": "   NameError: name 'BearerTokenizer' is not defined\n", "test_name": "test_get_user_order_by_id_of_diffrent_user", "rerun": "0"}, "20": {"status": "ERROR", "message": "file C:\\development\\eshop_test\\tests\\test_eshop.py, line 754\n  def test_get_user_orders(order_api):\nE       fixture 'order_api' not found\n>       available fixtures: anyio_backend, anyio_backend_name, anyio_backend_options, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, extra, include_metadata_in_junit_xml, metadata, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\development\\eshop_test\\tests\\test_eshop.py:754\n", "test_name": "test_get_user_orders", "rerun": "0"}, "21": {"status": "FAIL", "message": "   pyodbc.InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')\n", "test_name": "test_update_order_to_shiped_to_diffrent_user", "rerun": "0"}}, "suite_name": "tests/test_eshop.py"}}}, "date": "March 19, 2023", "start_time": 1679229117.2127886, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "21", "skip": "0", "error": "1", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "22"}